version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-trackapi
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trackdb
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: